# Generated by Django 4.2.26 on 2025-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото для этой услуги",
                null=True,
                upload_to="services/%Y/%m/%d/",
                verbose_name="Фото услуги",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.CharField(blank=True, max_length=100, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название услуги"),
        ),
    ]
