# Generated by Django 4.2.26 on 2025-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_service_options_service_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Рекомендуемый размер: 800x600px",
                null=True,
                upload_to="services/%Y/%m/%d/",
                verbose_name="Фото услуги",
            ),
        ),
    ]
