# Generated by Django 4.2.26 on 2025-11-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_service_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={"verbose_name": "Галерея", "verbose_name_plural": "Галерея"},
        ),
    ]
