# Generated by Django 4.2.26 on 2025-11-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_galleryimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(5, '5 - Отлично'), (4, '4 - Хорошо'), (3, '3 - Удовлетворительно'), (2, '2 - Плохо'), (1, '1 - Очень плохо')], default=5, verbose_name='Оценка')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
