# Generated by Django 4.2.26 on 2025-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
    ]
